# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wO06cxcI4o1VLK3XfnYd4X7i_JiVAgc
"""

# Person/Animal Classifier - Training Notebook

## Dataset
- Custom dataset of 297 images labeled with two classes: `Animal` (class 0) and `Person` (class 1).
- Labels were pre-annotated and provided in YOLO format.

## Purpose
This notebook trains a YOLOv8n model to detect and classify persons and animals in images.

!unzip -q "/content/Label_file.zip" -d /content/

!ls -la /content/

import os
import shutil

# Find the extracted folder (adjust the name if different)
if os.path.exists("/content/Label_file"):
    shutil.move("/content/Label_file", "/content/custom_data")
elif os.path.exists("/content/export"):
    shutil.move("/content/export", "/content/custom_data")
else:
    # If you see a different folder name, replace it below
    print("Check the folder name with !ls")

!ls /content/custom_data/

!ls -la /content/

import os

# Create custom_data directory
os.makedirs("/content/custom_data", exist_ok=True)

# Move the folders and files
!mv /content/images /content/custom_data/
!mv /content/labels /content/custom_data/
!mv /content/classes.txt /content/custom_data/
!mv /content/notes.json /content/custom_data/ 2>/dev/null

# Verify
!ls -la /content/custom_data/

!cat /content/custom_data/classes.txt

!ls /content/custom_data/data.yaml

import yaml

# Match exactly what's in classes.txt (Animal first, Person second)
class_names = ['Animal', 'Person']

data = {
    'path': '/content/custom_data',
    'train': 'images',
    'val': 'images',
    'nc': 2,
    'names': class_names
}

with open('/content/custom_data/data.yaml', 'w') as f:
    yaml.dump(data, f, default_flow_style=False)

print("✅ data.yaml created")
print(f"   Class order: {class_names}")
print(f"   Class 0 = {class_names[0]}")
print(f"   Class 1 = {class_names[1]}")

import os

print("📁 Dataset Check:")
print(f"  images folder: {'✅' if os.path.exists('/content/custom_data/images') else '❌'}")
print(f"  labels folder: {'✅' if os.path.exists('/content/custom_data/labels') else '❌'}")
print(f"  classes.txt: {'✅' if os.path.exists('/content/custom_data/classes.txt') else '❌'}")
print(f"  data.yaml: {'✅' if os.path.exists('/content/custom_data/data.yaml') else '❌'}")

print("\n📋 classes.txt content:")
!cat /content/custom_data/classes.txt

print("\n📋 data.yaml content:")
!cat /content/custom_data/data.yaml

import os

label_dir = "/content/custom_data/labels/"
counts = {0: 0, 1: 0}

for file in os.listdir(label_dir)[:10]:  # Check first 10 files
    with open(os.path.join(label_dir, file), 'r') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 1:
                class_id = int(parts[0])
                counts[class_id] += 1

print(f"Class 0 (Animal) count in first 10 label files: {counts[0]}")
print(f"Class 1 (Person) count in first 10 label files: {counts[1]}")

# First, enable GPU: Runtime → Change runtime type → T4 GPU

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.train(
    data="/content/custom_data/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    device=0
)

from ultralytics import YOLO
from IPython.display import Image as IPImage, display

# Load your model
model = YOLO("/content/runs/detect/train-2/weights/best.pt")

# Print the class mapping
print(f"Model classes: {model.names}")

# Test on your image
results = model("/content/file(1).jpg")

# Save and display
results[0].save("test_result.jpg")
display(IPImage("test_result.jpg"))

# Print detections
print("\nDetections:")
for box in results[0].boxes:
    class_id = int(box.cls[0])
    confidence = float(box.conf[0])
    print(f"{model.names[class_id]} — {confidence:.2f}")

from google.colab import drive
drive.mount('/content/drive')

# Copy model to Drive
!cp /content/runs/detect/train-2/weights/best.pt /content/drive/MyDrive/best_model.pt

# Also copy the entire training folder (optional)
!cp -r /content/runs/detect/train-2 /content/drive/MyDrive/yolo_training_complete

print("✅ Model saved to Google Drive")

!pip install ultralytics

from ultralytics import YOLO
from IPython.display import Image as IPImage, display

# Load your model
model = YOLO("/content/drive/MyDrive/yolo_trained_model/weights/best.pt")

!find /content -name "*.pt" 2>/dev/null

from ultralytics import YOLO
from IPython.display import Image as IPImage, display

# Load your model
model = YOLO("/content/drive/MyDrive/best_model.pt")

# Print the class mapping
print(f"Model classes: {model.names}")

# Test on your image
results = model("/content/file(2).jpg")

# Save and display
results[0].save("test_result.jpg")
display(IPImage("test_result.jpg"))

# Print detections
print("\nDetections:")
for box in results[0].boxes:
    class_id = int(box.cls[0])
    confidence = float(box.conf[0])
    print(f"{model.names[class_id]} — {confidence:.2f}")